export const data = [
    {   
        id:"1",
        roomNumber:101,
        price:10000,
        type:'Standard',
        status:'Available'
    },
    {   
        id:"2",
        roomNumber:102,
        price:10000,
        type:'Standard',
        status:'Available'
    },
    {   
        id:"3",
        roomNumber:103,
        price:10000,
        type:'Standard',
        status:'Available'
    },
    {   
        id:"4",
        roomNumber:104,
        price:10000,
        type:'Standard',
        status:'Available'
    },
    {   
        id:"5",
        roomNumber:105,
        price:10000,
        type:'Standard',
        status:'Available'
    },
    {   
        id:"6",
        roomNumber:106,
        price:10000,
        type:'Standard',
        status:'Available'
    }
]